name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments

kramdown:
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
    enable_coderay: false
    input: GFM
